- id: doi:10.1101/2025.06.30.25330574
  tags: [biobank, population health, COVID19]
- id: doi:10.1101/2025.06.23.661117
  tags: [autoimmunity, type 1 diabetes, omics, trainee lead]
- id: doi:10.3390/ijms25147620
  tags: [developmental origin, omics, trainee lead]
- id: pmid:38915393
  tags: [autoimmunity, type 1 diabetes, omics]
- id: doi:10.1038/s41467-024-48507-7
  tags: [omics, allergic disease, genetics]
- id: doi:10.1155/2023/5367637
  tags: [developmental origin, autoimmunity, type 1 diabetes, omics, causal inference, trainee lead]
- id: doi:10.3390/nu15040945
  tags: [autoimmunity, type 1 diabetes, trainee lead, nutrition] 
- id: doi:10.3390/ijerph20032368
  tags: [biobank, population health, trainee lead, COVID19, genetics]
- id: doi:10.2337/db21-1111
  tags: [autoimmunity, type 1 diabetes, omics]
- id: doi:10.2196/37327
  tags: [biobank, population health, trainee lead, COVID19]
- id: doi:10.1016/j.jaci.2021.11.002
  tags: [omics, causal inference, allergic disease, genetics]
- id: pmid:35304161
  tags: [omics, allergic disease]
- id: doi:10.1101/2022.02.15.22271018
- id: doi:10.3390/nu13114057
  tags: [omics, trainee lead, nutrition]
- id: pmid:34496950
  tags: [autoimmunity, type 1 diabetes, omics]
- id: doi:10.3390/metabo11080542
  tags: [autoimmunity, type 1 diabetes, omics, casual inference, trainee lead]
- id: doi:10.1007/s00125-021-05446-y
  tags: [developmental origin, autoimmunity, type 1 diabetes, nutrition]
- id: doi:10.1038/s41390-020-1084-2
  tags: [omics, trainee lead, nutrition, genetics]
- id: pmid:33863802
  tags: [autoimmunity, type 1 diabetes, omics, trainee lead]
- id: doi:10.1111/1753-0407.13093
  tags: [autoimmunity, type 1 diabetes, omics, genetics]
- id: doi:10.1111/pedi.13085
  tags: [autoimmunity, type 1 diabetes, omics, trainee lead, nutrition]
- id: pmid:32651851
  tags: [autoimmunity, trainee lead, nutrition]
- id: doi:10.1111/pedi.12995
  tags: [autoimmunity, type 1 diabetes, omics, trainee lead, genetics]
- id: pmid:32333871
  tags: [type 1 diabetes]
- id: doi:10.1038/s41598-020-60758-0
  tags: [autoimmunity, type 1 diabetes, trainee lead]
- id: pmid:31999944
  tags: [autoimmunity, type 1 diabetes]
- id: doi:10.1017/jns.2020.9
  tags: [ trainee lead, nutrition]
- id: pmid:31715316
  tags: [autoimmunity, type 1 diabetes, trainee lead]
- id: pmid:31616039
  tags: [autoimmunity, type 1 diabetes, omics, trainee lead, nutrition]
- id: pmid:31082869
  tags: [autoimmunity, trainee lead, nutrition]
- id: pmid:30796108
  tags: [autoimmunity, type 1 diabetes, trainee lead, nutrition]
- id: pmid:30795754
  tags: [population health, trainee lead]
- id: doi:10.2105/AJPH.2015.302711
  tags: [population health, trainee lead]

