- id: doi:10.1101/2025.06.30.25330574
  tags: [ vaccine hesitancy, demographic factors, health conditions, trust in science]
- id: doi:10.1101/2025.06.23.661117
  tags: [immunology, type1diabetes, autoimmunity]
- id: doi:10.3390/ijms25147620
  tags: [metabolomics, obesity, pregnancy]
- id: pmid:38915393
  tags: [epigenetics, autoimmunity, longitudinal]
- id: doi:10.1038/s41467-024-48507-7
  tags: [multiomics, asthma, african diaspora, epithelium]
- id: doi:10.1155/2023/5367637
  tags: [DNA methylation, genetics, type1diabetes]
- id: doi:10.3390/nu15040945
  tags: [nutrients, oxylipins, type1diabetes]
- id: doi:10.3390/ijerph20032368
  tags: [COVID-19, mortality, biobank]
- id: doi:10.2337/db21-1111
  tags: [immunity, coexpression, diabetes]
- id: doi:10.2196/37327
  tags: [COVID-19, surveillance, biobank]
- id: doi:10.1016/j.jaci.2021.11.002
  tags: [metabolite, asthma, QTL]
- id: pmid:35304161
  tags: [lipid mediators, asthma, nasal epithelium]
- id: doi:10.1101/2022.02.15.22271018
  tags: [COVID-19, biobank, surveillance]
- id: doi:10.3390/nu13114057
  tags: [epigenetics, infant feeding, DNA methylation]
- id: pmid:34496950
  tags: [DNA methylation, pipeline, epidemiology]
- id: doi:10.3390/metabo11080542
  tags: [mediation, metabolome, methylation, diabetes]
- id: doi:10.1007/s00125-021-05446-y
  tags: [maternal nutrition, pregnancy, type1diabetes]
- id: doi:10.1038/s41390-020-1084-2
  tags: [oxylipins, pediatrics, metabolomics]
- id: pmid:33863802
  tags: [phospholipids, autoimmunity, diabetes]
- id: doi:10.1111/1753-0407.13093
  tags: [prediction, autoantibodies, diabetes]
- id: doi:10.1111/pedi.13085
  tags: [metabolomics, nutrient patterns, seroconversion]
- id: pmid:32651851
  tags: [gluten, thyroid autoantibodies, diabetes]
- id: doi:10.1111/pedi.12995
  tags: [DNA methylation, INS gene, diabetes]
- id: pmid:32333871
  tags: [type1diabetes, epidemiology, commentary]
- id: doi:10.1038/s41598-020-60758-0
  tags: [DNA methylation, longitudinal, diabetes]
- id: pmid:31999944
  tags: [type1diabetes, early origins, epidemiology]
- id: doi:10.1017/jns.2020.9
  tags: [diet, sugar intake, biomarkers]
- id: pmid:31715316
  tags: [vitamin D, chromatography, epimers]
- id: pmid:31616039
  tags: [diet, metabolite patterns, autoimmunity]
- id: pmid:31082869
  tags: [gluten, celiac disease, cohort study]
- id: pmid:30796108
  tags: [gluten, islet autoimmunity, diabetes]
- id: pmid:30795754
  tags: [adolescent health, survey, Guatemala]
- id: doi:10.2105/AJPH.2015.302711
  tags: [birth outcomes, public health, pregnancy]
